server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://v55fyvloi7sabacn:qco375co7k94fhdn@qbct6vwi8q648mrn.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/p9xumrx3l76am608
        username: v55fyvloi7sabacn
        password: qco375co7k94fhdn

    jpa:
        hibernate:
            ddl-auto: update

logging:
    level:
        root: info
