server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mobilestore?verifyServerCertificate=false&useSSL=false&requireSSL=false
        username: root
        password: root

    jpa:
        hibernate:
            ddl-auto: create-drop

logging:
    level:
        root: info